### ISSUE TITLE
Switch to Open Source Language Model

### ISSUE THREAD

**Issue by LuisSchuimer** [BytezoTeam/Eventfully#10]
Find a Local Language Model, for the categorisation and for extracting information from e-mail newsletters.

**Comment by 2mal3** [comment]
https://docs.mistral.ai/ could be a candidate for an open source cloud based llm

**Comment by LuisSchuimer** [comment]
GPT4ALL for a local model. It is also free to use. But is slow on week hardware [https://gpt4all.io/index.html](https://gpt4all.io/index.html)

**Comment by LuisSchuimer** [comment]
Or download a LLM (Large Language Model) and train it to give us the results we need. 

Pros:
- Reconfigure LLM to work faster on slow hardware
- Good results, because the LLM is trained to categorize
- Free

Cons:
- Much time needed for configuration
- Need to find a LLM for commercial use

**Comment by 2mal3** [comment]
With this approach, we need a huge amount of training data.

**Comment by 2mal3** [comment]
We asked. We have to use open source, so ChatGPT is not an option.

**Comment by 2mal3** [comment]
Mistral 7B or Mistral 8X7B looks promising. Both open source and have the similar quality of Chat GPT 3.5. They work locally, but Mistral also provides a cloud option for them.  
[Link](https://docs.mistral.ai/models/)

**Comment by 2mal3** [comment]
We don't need AI for our service for now.
