### ISSUE TITLE
Remove Age Property for Event?

### ISSUE THREAD

**Issue by 2mal3** [BytezoTeam/Eventfully#12]

**Comment by LuisSchuimer** [comment]
What do you mean with Age Property?

**Comment by 2mal3** [comment]
[eventfully/database.py](https://github.com/BytezoTeam/Eventfully/blob/main/eventfully/database.py)
```python
class Event(BaseModel):
    ...
    age: str
    ...
```

It is questionable whether you can even get age data from most event sources. Even with AI it might be difficult.

**Comment by 2mal3** [comment]
Happened with #50
