### ISSUE TITLE
Design New Website Skeleton

### ISSUE THREAD

**Issue by 2mal3** [BytezoTeam/Eventfully#4]

**Comment by LuisSchuimer** [comment]
[](https://tailwindcss.com/) for design?

**Comment by LuisSchuimer** [comment]
[https://tailwindcss.com/](url) for design?

**Comment by 2mal3** [comment]
### Pros:
- more control over the design (we are not bound to specific bootstrap components)
- more individual style (not typical bootstrap you know from everywhere)

### Con:
- more time consuming to implement (we can't rely on pre-built components)
- harder to make look nice (no perfectly designed components, we have to see for ourselves what looks good and how to implement a responsive layout)
- increases complexity (to make it work well, we need an additional _javascript based_ build system)

**Comment by LuisSchuimer** [comment]
Okay! We can talk about it with @BlitzBenedikt in the next conference

**Comment by LuisSchuimer** [comment]
He is the one who does design and the frontend
