### ISSUE TITLE
Crowdsourcing: Eventfully

### ISSUE THREAD

**Issue by LuisSchuimer** [BytezoTeam/Eventfully#45]
Making it possible to make an Account as a Organisator, to make and publish Events. 

Possible Features:
1. Making a direct form on our site, to login into Events (Form Builder)
2. Build a system to generate QR-Codes to login into events, when you are there

Would you think that this would be a nice idea to have more events?

**Comment by 2mal3** [comment]
Good idea and probably important to make Eventfully really usable. I think the most important thing is that organizers can publish events themselves. You can also implement a registration system for events, but organizers probably already have their own systems that they don't want to change.

**Comment by LuisSchuimer** [comment]
made in 083e2bf
