### ISSUE TITLE
Seperating Docker Stages

### ISSUE THREAD

**Issue by kaindlnetwork** [BytezoTeam/Eventfully#70]
Hi there,

The current Dockerfile does not seperate between using Eventfully in Production and Compiling the Image.
Is it nessesary to have `tailwindcss-extra` installed as dependency in the Image ?
My recommendation is to create a second `From` and a `COPY` to reduce not needed dependencies.

Best Regards

Fabian

**Comment by 2mal3** [comment]
Hi, thank you very much for all your help. Sounds good, the Dockerfile needs to be overhauled anyway.
