### ISSUE TITLE
Account System

### ISSUE THREAD

**Issue by 2mal3** [BytezoTeam/Eventfully#8]

**Comment by LuisSchuimer** [comment]
Fist Version: [https://github.com/BytezoTeam/Eventfully/commit/2e68fd3d13b1e8fb76d8d22578a3772b25a884ae](url)

TODO: 
In main.py (WebServer)
(36, 3) # TODO: Implementing Password and Username Check
(42, 3) # TODO: Implement Signin (WebSite)
(48, 3) # TODO: Implement Login (WebSite)

**Comment by LuisSchuimer** [comment]
@BlitzBenedikt can we talk over how we design the Signin and Login pages on the website. We also need a Account-Managing Site and more changes to the website

**Comment by LuisSchuimer** [comment]
First Update: [https://github.com/BytezoTeam/Eventfully/commit/fce47272c9206ab4416c0d2629d6d84b1fd36c30](url)

Added Username and Password Check (For Login)
Added Method to set a cookie

ToDo (New):
In utils.py:
(22, 3) # TODO: For safety: Add check to look if UserID already exists

**Comment by LuisSchuimer** [comment]
Second Update: [Commit](https://github.com/BytezoTeam/Eventfully/commit/534f079ea50e9d77dc04fecb37cc34118cfbf125)

Added delete
Renamed subdomains
Fixed Security Risk
Added Logout
Added "email" flag to database and login

**Comment by LuisSchuimer** [comment]
Security Update: [Commit](https://github.com/BytezoTeam/Eventfully/commit/9e2ec754eeeacf77efbf2d15519324f37e98169e)

Added secure, httponly Tags to cookie creation

**SonarCloud Check now passed!**

**Comment by 2mal3** [comment]
Basic Implementation Done

**Comment by LuisSchuimer** [comment]
Finished! YAAAAAAAAAAAAAYYYYYYYYYYYYYYY
