### ISSUE TITLE
Adding Impressum

### ISSUE THREAD

**Issue by kaindlnetwork** [BytezoTeam/Eventfully#87]
Hi there,
The Eventfully Website needs an Impressum.

https://www.e-recht24.de/artikel/datenschutz/209.html

Best Regards

Fabian

**Comment by 2mal3** [comment]
Thanks for the reminder, we will discuss this in our group as soon as possible. Probably needs #80 to be fully implemented.

**Comment by 2mal3** [comment]
Done

**Comment by kaindlnetwork** [comment]
Hi everybody,

A) "Imprint" is not the correct translation for "Impressum"

https://allcodesarebeautiful.com/impressum-auf-englisch-imprint-falsche-uebersetzung/

B) Please add the Country Code +49 in the Telephone Number :)

Please Reopen the issue.

Best Regards

Fabian
